--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/STCraftNetwork/RankSystemST
build-by-default: true
branches:
- main
projects:
  RankSystemST:
libs:
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^2.1.1
    path: ""
...
