---
name: RankSystemST
version: 1.0.0
main: KanadeBlue\RankSystemST\RankSystem
api: 5.17.0
src-namespace-prefix: KanadeBlue\RankSystemST

permissions:
  command.rank.set:
    default: op
  command.rank.create:
    default: op
  command.permission.add:
    default: op

...
